#!/bin/bash
echo
while true; do
	echo "Select an option [1-9]"
	echo "-----------------------"
	echo "1.Create a new directory"
	echo "2.Delete an existing directory"
	echo "3.List the contents of a directory"
	echo "4.Change into a directory"
	echo "5.Create a new file"
	echo "6.Write to an existing file"
	echo "7.Read from an existing file"
	echo "8.Delete an existing file"
	echo "9.Exit the script."

	read choice

case $choice in
	1)
	
		echo "Enter the name of the newdirectory:"
		read dirname
		mkdir $dirname
		echo	
		if [ $? -eq 0 ]
		then
			echo "Successful"
			echo
		else
			echo "Not Successful"
			echo
		fi
		;;
	
	2)
	
		echo "Enter the name of the directory to delete:"
		read deldir
		rm -rf $deldir
		echo
	
		if [ $? -eq 0 ]
		then
			echo "Successful"
			echo
		else
			echo "Not Successful"
			echo
		fi
		;;
	
	3)
	
		echo  "Are you in the right directory (y/n): "
		read input	
		#while true; do
			if [ $input == "n" ]
			then
				echo -e "Change your directory"
				echo
				
			elif [ $input == "y" ]
			then 
		
				ls -l
 				echo
			else 
			
				echo "Wrong choice"
				echo "Enter y or n"
				echo
			fi
		#done
		
		if [ $? -eq 0 ]
		then
			echo "Successful"
			echo
		else
			echo "Not Successful"
			echo
		fi
		;;
	4)
	
		echo "Enter the name of the directory:"
		read chdir
		cd $chdir
		echo
	
		if [ $? -eq 0 ]
		then
			echo Successful
			echo
		else
			echo Not Successful
			echo
		fi
		;;
		
	5)
		echo "Are you in the right directory (y/n): "
		read input
	
		if [ $input == "n" ]
		then
			echo -e "Change your directory"
			echo
		elif [ $input == "y" ]
		then 
			echo -e "Enter the new file name"
			read newfile
			touch $newfile
			echo
 				
		else 
			
			echo "Wrong choice"
			echo "Enter y or n"
			echo
				
		fi

		if [ $? -eq 0 ]
		then
			echo Successful
		else
			echo Not Successful
			echo
		fi
		;;
	
	6)
	
		echo "Are you in the right directory (y/n): "
		read input
		echo
	
		if [ $input == "n" ]
		then
			echo -e "Change your directory"
				
		elif [ $input == "y" ]
		then 
			echo -e "Enter the file name"
			read writefile
			cat >> $writefile
				
 		else 
			
			echo "Wrong choice"
			echo "Enter y or n"
		echo	
		fi
		
		
		if [ $? -eq 0 ]
		then
			echo Successful
		else
			echo Not Successful
		echo
		fi
		;;
	7)
	
		echo "Are you in the right directory (y/n): "
		read input
		echo
		if [ $input == "n" ]
		then
			echo -e "Change your directory"
		elif [ $input == "y" ]
		then	
			echo "Enter the name of file: "
			read readfile
			cat $readfile
		else
			echo -e "Wrong Choice"
			echo -e "Enter y or n"
		echo
		fi
		
		
		if [ $? -eq 0 ]
		then
			echo Successful
		else
			echo Not Successful
		echo
		fi
		;;
	
	8)
	
		echo "Are you in the right directory (y/n): "
		read input
		echo
	
		if [ $input == "n" ]
		then
			echo -e "Change your directory"
		elif [ $input == "y" ]
		then
			echo "Enter the name of file: "
			read defile
			rm $delfile
			
		else 
			echo -e "Wrong Choice"
			echo -e "Enter y or n"
		echo
		fi
		
		if [ $? -eq 0 ]
		then
			echo Successful
		else
			echo Not Successful
		echo
		fi
		;;
	9)
		exit 1
		;;
esac
done
